export const themeConfig = {
  festival: {
    bg        : 'bg-festival-main',
    text      : 'text-festival-main',
    dateText  : 'text-festival-main',
    badgeBg   : 'bg-festival-main/15',
    badgeText : 'text-festival-main',

    hoverTitle: 'group-hover:text-festival-main',
    btnHover  : 'hover:bg-festival-main hover:text-white hover:border-festival-main',
    gradient  : 'from-festival-main to-festival-accent',
    border    : 'border-festival-main/30',
  },
  teatro: {
    bg        : 'bg-teatro-main',
    text      : 'text-teatro-main',
    dateText  : 'text-teatro-main',
    badgeBg   : 'bg-teatro-main/15',
    badgeText : 'text-teatro-main',
    hoverTitle: 'group-hover:text-teatro-main',
    btnHover  : 'hover:bg-teatro-main hover:text-white hover:border-teatro-main',
    gradient  : 'from-teatro-main to-teatro-accent',
    border    : 'border-teatro-main/30',
  },
  corporativo: {
    bg        : 'bg-corporativo-main',
    text      : 'text-corporativo-main',
    dateText  : 'text-corporativo-main',
    badgeBg   : 'bg-corporativo-main/15',
    badgeText : 'text-corporativo-main',
    hoverTitle: 'group-hover:text-corporativo-main',
    btnHover  : 'hover:bg-corporativo-main hover:text-white hover:border-corporativo-main',
    gradient  : 'from-corporativo-main to-corporativo-accent',
    border    : 'border-corporativo-main/30',
  },
  deporte: {
    bg        : 'bg-deporte-main',
    text      : 'text-deporte-main',
    dateText  : 'text-deporte-main',
    badgeBg   : 'bg-deporte-main/15',
    badgeText : 'text-deporte-main',
    hoverTitle: 'group-hover:text-deporte-main',
    btnHover  : 'hover:bg-deporte-main hover:text-white hover:border-deporte-main',
    gradient  : 'from-deporte-main to-deporte-accent',
    border    : 'border-deporte-main/30',
  },
  conferencia: {
    bg        : 'bg-conferencia-main',
    text      : 'text-conferencia-main',
    dateText  : 'text-conferencia-main',
    badgeBg   : 'bg-conferencia-main/15',
    badgeText : 'text-conferencia-main',
    hoverTitle: 'group-hover:text-conferencia-main',
    btnHover  : 'hover:bg-conferencia-main hover:text-white hover:border-conferencia-main',
    gradient  : 'from-conferencia-main to-conferencia-accent',
    border    : 'border-conferencia-main/30',
  },
  default: {
    bg        : 'bg-primary',
    text      : 'text-primary',
    dateText  : 'text-primary',
    badgeBg   : 'bg-primary/15',
    badgeText : 'text-primary',
    hoverTitle: 'group-hover:text-primary',
    btnHover  : 'hover:bg-primary hover:text-white hover:border-primary',
    gradient  : 'from-primary to-secondary',
    border    : 'border-primary/30',
  },
};

export const categoriaLabels = {
  festival   : 'Festival',
  teatro     : 'Teatro / Arte',
  corporativo: 'Corporativo',
  deporte    : 'Deportes',
  conferencia: 'Conferencia',
};